module.exports = {
  content: [
    './**/*.html',
    './**/*.php',   
    './**/*.js'
  ],
  safelist: [
    'text-black-200',
    'text-lg',
    'mb-2',
    'text-sm',
    'text-green-500',
    'mt-6',
    'inline-block',
    'bg-blue-500',
    'hover:bg-blue-600',
    'text-white',
    'font-medium',
    'py-2',
    'px-4',
    'rounded',
    'transition',
    'container',
        'mx-auto',
        'p-8',
        'text-3xl',
        'font-bold',
        'mb-8',
        'bg-white',
        'p-6',
        'rounded-lg',
        'shadow-lg',
        'mb-6',
        'text-xl',
        'font-semibold',
        'space-y-4',
        'block',
        'text-sm',
        'font-medium',
        'text-gray-700',
        'w-full',
        'p-3',
        'border',
        'rounded-lg',
        'bg-blue-500',
        'text-white',
        'min-w-full',
        'table-auto',
        'px-4',
        'py-2',
        'inline',
        'space-x-2',
        'bg-green-500',
        'bg-red-500',
        'text-gray-500'
  ],
  theme: {
    extend: {
      animation: {
        'spin-slow': 'spin 6s linear infinite',
      },
    },
  },
  plugins: [],
}
